name: Build & Deploy Quartz to GitHub Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Quartz project (quartz branch in this repo)
        uses: actions/checkout@v3
        with:
          ref: quartz
          path: site

      - name: Checkout content from external repo (zjc-content/main)
        uses: actions/checkout@v3
        with:
          repository: ZhouSSS/zjc-content         
          ref: main
          token: ${{ secrets.CONTENT_REPO_TOKEN }} 
          path: content

      - name: Sync content into Quartz site
        run: |
          rm -rf site/content
          mkdir -p site/content
          cp -r content/* site/content/

      - name: Install dependencies & build Quartz
        run: |
          cd site
          npm ci
          npx quartz build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site/public
          publish_branch: main   
          force_orphan: true   
