name: Build & Deploy Quartz to GitHub Pages

on:
  push:
    branches:
      - quartz

  workflow_dispatch:
  repository_dispatch:
    types: [build_and_deploy_quartz]  # 这里必须和你 curl 请求里的 event_type 保持一致

jobs:
  deploy:
    #if: >
     # github.event_name == 'push' ||
     # github.event_name == 'workflow_dispatch' ||
     # (github.event_name == 'repository_dispatch' && github.event.action == 'build_and_deploy_quartz')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Quartz project (quartz branch in this repo)
        uses: actions/checkout@v3
        with:
          ref: quartz
          path: site

      - name: Checkout content from external repo (zjc-content/main)
        uses: actions/checkout@v3
        with:
          repository: ZhouSSS/zjc-content
          ref: main
          token: ${{ secrets.CONTENT_REPO_TOKEN }}
          path: content

      - name: Sync content into Quartz site
        run: |
          rm -rf site/content
          mkdir -p site/content
          cp -r content/* site/content/

      - name: Install dependencies & build Quartz
        run: |
          cd site
          npm ci
          npx quartz build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site/public
          publish_branch: main
          force_orphan: true
