name: Build & Deploy Quartz to GitHub Pages

on:
  push:
    branches:
      - content # 当 content 分支有更新时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Quartz project (quartz branch)
        uses: actions/checkout@v3
        with:
          ref: quartz
          path: site

      - name: Checkout content (content branch)
        uses: actions/checkout@v3
        with:
          ref: content
          path: content

      - name: Sync content to Quartz
        run: |
          rm -rf site/content
          mkdir -p site/content
          cp -r content/* site/content/

      - name: Install dependencies & build Quartz
        run: |
          cd site
          npm ci
          npx quartz build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site/public
          publish_branch: main # ✅ 改为 main 分支
          force_orphan: true # ✅ 保证 main 分支完全覆盖（清空再部署）
